language: c
sudo: false
dist: trusty
addons:
    apt:
        packages:
        - ninja
        #- gcc-mingw-w64-i686
        #- libz-mingw-w64-dev
        #- nsis
        - liblua5.1-dev
        - liblua5.2-dev
        - liblua5.3-dev
        - libluajit5.1-dev
script:
    - make -j4 dev

