language: c

compiler:
    - gcc
    - clang

os:
    -
        os: osx
        osx_image: xcode10.2

    -
        os: linux

addons:
    apt:
        packages:
        - ninja-build
        #- gcc-mingw-w64-i686
        #- libz-mingw-w64-dev
        #- nsis
        - liblua5.1-dev
        - liblua5.2-dev
        #- liblua5.3-dev
        #- libluajit5.1-dev
    homebrew:
        packages:
        - ninja
        - lua

script:
    - make -j4 dev
